# Generated by Django 3.1.13 on 2021-11-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelslist',
            name='hotel_locations',
        ),
        migrations.AddField(
            model_name='hotelslist',
            name='hotel_locations',
            field=models.ManyToManyField(default='  ', to='appTwo.HotelLocation'),
        ),
    ]
