# Generated by Django 3.1.13 on 2021-11-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0002_auto_20211112_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellocation',
            name='hotel_locations',
            field=models.CharField(max_length=264, primary_key=True, serialize=False, unique=True),
        ),
    ]
