# Generated by Django 3.1.13 on 2021-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0003_auto_20211112_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellocation',
            name='hotel_locations',
            field=models.CharField(max_length=264, primary_key=True, serialize=False),
        ),
    ]
