# Generated by Django 3.1.13 on 2021-11-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0005_auto_20211112_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelslist',
            name='hotel_locations',
        ),
    ]
