# Generated by Django 3.1.13 on 2021-11-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0006_remove_hotelslist_hotel_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelslist',
            name='hotel_locations',
            field=models.ManyToManyField(default='  ', to='appTwo.HotelLocation'),
        ),
    ]
