# Generated by Django 3.1.13 on 2021-11-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0007_hotelslist_hotel_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelslist',
            name='hotel_menu',
        ),
    ]
