# Generated by Django 3.1.13 on 2021-11-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0008_remove_hotelslist_hotel_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelslist',
            name='hotel_menu',
            field=models.ManyToManyField(default='  ', to='appTwo.ItemsList'),
        ),
    ]
