# Generated by Django 3.2.11 on 2022-01-17 08:29

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'db_table': 'asset_tracker_Asset_Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('employee', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'asset_tracker_employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeneralImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_image', models.ImageField(upload_to='general_image_uploades/')),
            ],
            options={
                'verbose_name': 'General Image',
                'verbose_name_plural': 'General Images',
                'db_table': 'asset_tracker_General_Images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'asset_tracker_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Skill Type',
                'verbose_name_plural': 'Skill Types',
                'db_table': 'asset_tracker_skill_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('skill_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_type', to='asset_tracker.skilltype')),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Skillss',
                'db_table': 'asset_tracker_skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Occupied', 'Occupied'), ('Available', 'Available')], max_length=50)),
                ('backend_tech_stack', smart_selects.db_fields.ChainedManyToManyField(chained_field='skill_type', chained_model_field='skill_type', horizontal=True, related_name='employee_backend_skills', to='asset_tracker.Skills')),
                ('cloud_tech_stack', smart_selects.db_fields.ChainedManyToManyField(chained_field='skill_type', chained_model_field='skill_type', horizontal=True, related_name='employee_cloud_skills', to='asset_tracker.Skills')),
                ('current_project', models.ManyToManyField(blank=True, related_name='employee_projects', to='asset_tracker.Projects')),
                ('current_project_skill', models.ManyToManyField(related_name='employee_current_skill', to='asset_tracker.Skills')),
                ('database_tech_stack', smart_selects.db_fields.ChainedManyToManyField(chained_field='skill_type', chained_model_field='skill_type', horizontal=True, related_name='employee_database_skills', to='asset_tracker.Skills')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_details_skills', to='asset_tracker.employee')),
                ('frontend_tech_stack', smart_selects.db_fields.ChainedManyToManyField(chained_field='skill_type', chained_model_field='skill_type', horizontal=True, related_name='employee_frontend_skills', to='asset_tracker.Skills')),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skill_type', to='asset_tracker.skilltype')),
            ],
            options={
                'verbose_name': 'Employee Skills',
                'verbose_name_plural': 'Employee Skills',
                'db_table': 'asset_tracker_employee_skills',
            },
        ),
        migrations.CreateModel(
            name='AssetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('system_id', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('purchased_date', models.DateField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('brand', models.CharField(max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('disk', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('license', models.CharField(blank=True, choices=[('Valid', 'valid'), ('Invalid', 'Invalid')], default='Valid', max_length=50, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('allocation', models.CharField(choices=[('Assigned', 'Assigned'), ('Unassigned', 'Unassigned'), ('Service', 'Service')], default='Assigned', max_length=50)),
                ('comments', models.CharField(blank=True, max_length=300)),
                ('system_image', models.ImageField(upload_to='system_image_uploades/')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='asset_tracker.assettype')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='asset_tracker.employee')),
            ],
            options={
                'verbose_name': 'Asset Tracker',
                'verbose_name_plural': 'Asset Trackers',
                'db_table': 'asset_tracker_Asset_Tracker',
                'managed': True,
            },
        ),
    ]
