# Generated by Django 3.2.11 on 2022-01-17 10:04

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='backend_tech_stack',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='cloud_tech_stack',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='database_tech_stack',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_type',
        ),
        migrations.AddField(
            model_name='skilltype',
            name='skill_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='skill_name', to='asset_tracker.Skills'),
        ),
        migrations.AlterField(
            model_name='employeeskills',
            name='frontend_tech_stack',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='skill_type', chained_model_field='skill_name', horizontal=True, related_name='employee_frontend_skills', to='asset_tracker.SkillType'),
        ),
    ]
