# Generated by Django 3.2.11 on 2022-01-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0007_alter_employeeskills_frontend_tech_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'CloudSkills',
                'verbose_name_plural': 'CloudSkillss',
                'db_table': 'asset_tracker_cloudskills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatabaseSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'DatabaseSkills',
                'verbose_name_plural': 'DatabaseSkillss',
                'db_table': 'asset_tracker_databaseskills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DevOpsSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'DevOpsSkills',
                'verbose_name_plural': 'DevOpsSkillss',
                'db_table': 'asset_tracker_devopsskills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FrontEndSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modeified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'FrontEndSkills',
                'verbose_name_plural': 'FrontEndSkillss',
                'db_table': 'asset_tracker_frontendskills',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='BackEndSkills',
        ),
        migrations.AlterModelOptions(
            name='backendskills',
            options={'managed': True, 'verbose_name': 'BackEndSkills', 'verbose_name_plural': 'BackEndSkillss'},
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='current_project_skill',
        ),
        migrations.RemoveField(
            model_name='skilltype',
            name='skill_name',
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='backend_tech_stack',
            field=models.ManyToManyField(blank=True, related_name='employee_backend_skills', to='asset_tracker.BackEndSkills'),
        ),
        migrations.AlterModelTable(
            name='backendskills',
            table='asset_tracker_backendskills',
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='cloud_tech_stack',
            field=models.ManyToManyField(blank=True, related_name='employee_cloud_skills', to='asset_tracker.CloudSkills'),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='database_tech_stack',
            field=models.ManyToManyField(blank=True, related_name='employee_database_skills', to='asset_tracker.DatabaseSkills'),
        ),
        migrations.AlterField(
            model_name='employeeskills',
            name='frontend_tech_stack',
            field=models.ManyToManyField(blank=True, related_name='employee_frontend_skills', to='asset_tracker.FrontEndSkills'),
        ),
    ]
