# Generated by Django 3.2.11 on 2022-01-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0008_auto_20220117_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeskills',
            name='skill_type',
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='skill_type',
            field=models.ManyToManyField(related_name='employee_skill_type', to='asset_tracker.SkillType'),
        ),
    ]
