# Generated by Django 3.2.11 on 2022-01-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0009_auto_20220117_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='backend_tech',
            field=models.ManyToManyField(related_name='project_backend_skill', to='asset_tracker.FrontEndSkills'),
        ),
        migrations.AddField(
            model_name='projects',
            name='devops_tech',
            field=models.ManyToManyField(related_name='project_devops_skill', to='asset_tracker.FrontEndSkills'),
        ),
        migrations.AddField(
            model_name='projects',
            name='frontend_tech',
            field=models.ManyToManyField(related_name='project_frontend_skill', to='asset_tracker.FrontEndSkills'),
        ),
        migrations.AddField(
            model_name='projects',
            name='product_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_product_manager', to='asset_tracker.employee'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_members',
            field=models.ManyToManyField(related_name='project_project_members', to='asset_tracker.Employee'),
        ),
    ]
