# Generated by Django 3.2.11 on 2022-01-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0010_auto_20220118_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='backend_tech',
            field=models.ManyToManyField(related_name='project_backend_skill', to='asset_tracker.BackEndSkills'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='devops_tech',
            field=models.ManyToManyField(related_name='project_devops_skill', to='asset_tracker.DevOpsSkills'),
        ),
    ]
