# Generated by Django 3.2.11 on 2022-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0011_auto_20220118_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_status',
            field=models.CharField(blank=True, choices=[('New', 'Occupied'), ('Open', 'Available'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
