# Generated by Django 3.2.11 on 2022-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0013_alter_projects_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('Intern', ' Intern'), ('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Business Associate', 'Business Associate'), ('HR Associate', 'HR Associate'), ('UI/UX Designer', 'UI/UX Designer'), ('Associate Business Manager', 'Associate Business Manager'), ('Senior HR Manager', 'Senior HR Manager'), ('Product Manager', 'Product Manager')], max_length=50),
        ),
    ]
